#!/usr/bin/env bash
# This script adds a custom nginx response header

# shellcheck disable=SC2154
sed -i '/server_name _;/a\        add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

service nginx restart
