#!/usr/bin/env bash
# This script configures nginx to add a custom X-Served-By header

apt-get update -y
apt-get install nginx -y

sed -i '/server_name _;/a\        add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

service nginx restart
