#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer

apt-get update -y
apt-get install haproxy -y

cat > /etc/haproxy/haproxy.cfg <<EOF
global
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server web-01 35.175.138.189:80 check
        server web-02 34.201.249.145:80 check
EOF

service haproxy restart
