#!/usr/bin/env bash
# This script installs and configures nginx web server

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx start
