#!/usr/bin/env bash
# This script configures nginx to redirect /redirect_me

sed -i '/server_name _;/a\
\        location /redirect_me {\
\                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\        }' /etc/nginx/sites-enabled/default

service nginx restart
