#!/usr/bin/env bash
# This script configures nginx with a custom 404 page

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a\
\	error_page 404 /404.html;' /etc/nginx/sites-enabled/default

service nginx restart
